# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xT_v87_0X1g8ye2dymESOVieHoxYoR-2
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import plotly.express as px
import plotly.graph_objects as go
import datetime

# --- CẤU HÌNH TRANG ---
st.set_page_config(page_title="Phân Tích Cấu Trúc VN30", page_icon="📈", layout="wide")

# CSS tùy chỉnh giao diện
st.markdown("""
    <style>
    .main-header { font-size: 2.2rem; font-weight: bold; color: #1E3A8A; margin-bottom: 5px;}
    .sub-header { font-size: 1.1rem; color: #64748B; margin-bottom: 20px;}
    .insight-box { background-color: #F0F9FF; padding: 15px; border-left: 5px solid #0EA5E9; border-radius: 5px; margin-bottom: 15px;}
    .breakthrough-box { background-color: #FFF1F2; padding: 15px; border-left: 5px solid #E11D48; border-radius: 5px; margin-bottom: 15px;}
    </style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-header">Phân Tích Cấu Trúc Thị Trường VN30 Bằng PCA</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Ứng dụng trực quan hóa thuật toán Machine Learning trong Tài chính</div>', unsafe_allow_html=True)

# --- SIDEBAR & CACHING DỮ LIỆU ---
st.sidebar.header("⚙️ Nguồn Dữ Liệu")

# Lấy code danh sách VN30 từ script gốc của bạn
vn30_tickers = [
    "ACB.VN", "BID.VN", "BVH.VN", "CTG.VN", "FPT.VN",
    "GAS.VN", "GVR.VN", "HDB.VN", "HPG.VN", "KDH.VN",
    "MBB.VN", "MSN.VN", "MWG.VN", "NLG.VN", "NVL.VN",
    "PDR.VN", "PLX.VN", "POW.VN", "SAB.VN", "SHB.VN",
    "SSB.VN", "SSI.VN", "STB.VN", "TCB.VN", "TPB.VN",
    "VCB.VN", "VHM.VN", "VIB.VN", "VIC.VN", "VNM.VN",
    "VPB.VN", "VRE.VN"
][:30]

@st.cache_data(ttl=3600)
def load_stock_data():
    end_date = datetime.date.today() - datetime.timedelta(days=1)
    start_date = end_date - datetime.timedelta(days=365)

    # Tải dữ liệu từ Yahoo Finance (Logic từ file untitled6.py)
    data = yf.download(vn30_tickers, start=start_date, end=end_date)['Close']
    data = data.ffill().dropna()
    return data

with st.spinner('Đang tải dữ liệu 30 mã từ Yahoo Finance (1 năm gần nhất)...'):
    df_prices = load_stock_data()

# Upload file VN30-Index thực tế
st.sidebar.markdown("---")
st.sidebar.markdown("**Tải lên file VN30-Index** (Tùy chọn)")
st.sidebar.info("Upload file VN30.csv của bạn để so sánh PC1 với chỉ số thực tế.")
uploaded_file = st.sidebar.file_uploader("Chọn file VN30.csv", type=["csv"])

df_vn30_index = None
if uploaded_file is not None:
    try:
        df_vn30_index = pd.read_csv(uploaded_file, parse_dates=['Ngày'], dayfirst=True)
        df_vn30_index = df_vn30_index.set_index('Ngày').sort_index()
        # Xử lý cột 'Lần cuối' (Giá đóng cửa)
        if 'Lần cuối' in df_vn30_index.columns:
            df_vn30_index['VN30_Close'] = df_vn30_index['Lần cuối'].astype(str).str.replace(',', '').astype(float)

        # Đồng bộ timezone
        df_vn30_index.index = df_vn30_index.index.tz_localize(None)
        df_prices.index = df_prices.index.tz_localize(None)
    except Exception as e:
        st.sidebar.error(f"Lỗi đọc file CSV: {e}")

# --- TIỀN XỬ LÝ & THUẬT TOÁN PCA ---
# 1. Tính lợi suất
df_returns = df_prices.pct_change().dropna()

# 2. Chuẩn hóa dữ liệu
df_returns_std = (df_returns - df_returns.mean()) / df_returns.std()

# 3. Tính ma trận hiệp phương sai
cov_matrix = np.cov(df_returns_std.T)

# 4. Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues = np.real(eigenvalues)
eigenvectors = np.real(eigenvectors)

# Sắp xếp giảm dần
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues_sorted = eigenvalues[sorted_indices]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

# Tính % phương sai giải thích
explained_variance_ratio = eigenvalues_sorted / np.sum(eigenvalues_sorted)
cumulative_variance = np.cumsum(explained_variance_ratio)

# Xây dựng các PC
pcs = df_returns_std.dot(eigenvectors_sorted)
pcs.columns = [f"PC{i+1}" for i in range(pcs.shape[1])]


# --- TẠO TABS HIỂN THỊ ---
tab1, tab2, tab3, tab4 = st.tabs([
    "1️⃣ Tiền xử lý Dữ liệu",
    "2️⃣ Thuật toán PCA",
    "3️⃣ So sánh PC1 & VN30",
    "🚀 Nghiên cứu Chuyên sâu"
])

with tab1:
    st.markdown("### Dữ liệu Giá Đóng Cửa (YFinance)")
    st.dataframe(df_prices.tail())

    st.markdown("### Dữ liệu Lợi Suất Chuẩn Hóa")
    st.dataframe(df_returns_std.tail())

    st.markdown('<div class="insight-box"><b>Tiền xử lý:</b> Dữ liệu được thu thập từ <code>yfinance</code>. Lợi suất hằng ngày được tính toán và chuẩn hóa (StandardScaler) để đảm bảo các cổ phiếu có thị giá cao không làm lệch mô hình PCA.</div>', unsafe_allow_html=True)

with tab2:
    st.markdown("### Xây dựng PCA bằng Ma trận Hiệp phương sai")
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Ma trận Hiệp phương sai (Covariance Matrix):**")
        fig_cov = px.imshow(cov_matrix, x=df_prices.columns, y=df_prices.columns, color_continuous_scale='RdBu_r')
        fig_cov.update_layout(width=500, height=500)
        st.plotly_chart(fig_cov, use_container_width=True)

    with col2:
        st.markdown("**Biểu đồ Scree Plot:**")
        fig_scree = go.Figure()
        fig_scree.add_trace(go.Bar(x=[f"PC{i+1}" for i in range(10)], y=explained_variance_ratio[:10]*100, name='Phương sai từng PC'))
        fig_scree.add_trace(go.Scatter(x=[f"PC{i+1}" for i in range(10)], y=cumulative_variance[:10]*100, mode='lines+markers', name='Phương sai tích lũy'))
        fig_scree.update_layout(yaxis_title="% Phương sai giải thích", hovermode="x unified")
        st.plotly_chart(fig_scree, use_container_width=True)

    st.markdown(f'<div class="insight-box"><b>Nhận xét:</b> Thành phần chính đầu tiên (PC1) giải thích được <b>{explained_variance_ratio[0]*100:.2f}%</b> biến động toàn thị trường.</div>', unsafe_allow_html=True)

with tab3:
    st.markdown("### Phân tích Thành Phần Chính PC1 (Yếu Tố Thị Trường)")

    col1, col2 = st.columns([1, 2])

    pc1_weights = eigenvectors_sorted[:, 0]
    # Đảo dấu nếu đa số là âm (quy ước toán học)
    if pc1_weights.mean() < 0:
        pc1_weights = -pc1_weights
        pcs['PC1'] = -pcs['PC1']

    with col1:
        st.markdown("**Trọng số cổ phiếu (PC1 Loadings):**")
        df_weights = pd.DataFrame({'Ticker': df_prices.columns, 'Weight': pc1_weights}).sort_values(by='Weight')
        fig_weights = px.bar(df_weights, x='Weight', y='Ticker', orientation='h', color='Weight', color_continuous_scale='Blues')
        fig_weights.update_layout(height=600)
        st.plotly_chart(fig_weights, use_container_width=True)

    with col2:
        st.markdown("**So sánh chuỗi thời gian: PC1 vs Chỉ số VN30:**")
        pc1_cum = (1 + pcs['PC1'] * 0.01).cumprod()

        fig_compare = go.Figure()

        if df_vn30_index is not None:
            common_dates = df_returns.index.intersection(df_vn30_index.index)
            if len(common_dates) > 0:
                vn30_returns_real = df_vn30_index.loc[common_dates, 'VN30_Close'].pct_change().dropna()
                vn30_cum_real = (1 + vn30_returns_real).cumprod()

                pc1_returns_matched = pcs.loc[vn30_returns_real.index, 'PC1']
                pc1_cum_matched = (1 + pc1_returns_matched * 0.01).cumprod()

                fig_compare.add_trace(go.Scatter(x=vn30_cum_real.index, y=pc1_cum_matched, mode='lines', name='Chỉ số PC1', line=dict(color='#0EA5E9', width=2)))
                fig_compare.add_trace(go.Scatter(x=vn30_cum_real.index, y=vn30_cum_real, mode='lines', name='VN30-Index Thực tế', line=dict(color='#E11D48', dash='dot')))

                corr = np.corrcoef(pc1_returns_matched, vn30_returns_real)[0, 1]
                st.metric("Hệ số tương quan (Correlation)", f"{corr:.4f}")
            else:
                st.warning("Ngày tháng trong file CSV chưa khớp với dữ liệu YFinance.")
        else:
            proxy_returns = df_returns.mean(axis=1)
            proxy_cum = (1 + proxy_returns).cumprod()
            fig_compare.add_trace(go.Scatter(x=df_returns.index, y=pc1_cum, mode='lines', name='Chỉ số PC1', line=dict(color='#0EA5E9', width=2)))
            fig_compare.add_trace(go.Scatter(x=proxy_cum.index, y=proxy_cum, mode='lines', name='VN30 Proxy (Equal Weight)', line=dict(color='#E11D48', dash='dot')))
            corr = np.corrcoef(pcs['PC1'], proxy_returns)[0, 1]
            st.metric("Hệ số tương quan (PC1 vs VN30 Proxy)", f"{corr:.4f}")
            st.info("💡 Vui lòng upload file VN30.csv từ bảng điều khiển bên trái (Sidebar) để so sánh với chỉ số thực tế.")

        fig_compare.update_layout(hovermode="x unified")
        st.plotly_chart(fig_compare, use_container_width=True)

with tab4:
    st.markdown("### 🚀 Phát Hiện Đột Phá: Sector Factors (Phân Cụm Ngành từ PC2 & PC3)")
    st.write("Sử dụng Machine Learning (PCA) để tự động nhận diện sự luân chuyển dòng tiền giữa các nhóm ngành mà không cần dán nhãn từ trước.")

    # Logic mapping ngành từ notebook của bạn
    sector_mapping = {
        "ACB.VN": "Ngân hàng", "BID.VN": "Ngân hàng", "CTG.VN": "Ngân hàng",
        "HDB.VN": "Ngân hàng", "MBB.VN": "Ngân hàng", "SHB.VN": "Ngân hàng",
        "SSB.VN": "Ngân hàng", "STB.VN": "Ngân hàng", "TCB.VN": "Ngân hàng",
        "TPB.VN": "Ngân hàng", "VCB.VN": "Ngân hàng", "VIB.VN": "Ngân hàng", "VPB.VN": "Ngân hàng",
        "VHM.VN": "Bất động sản", "VIC.VN": "Bất động sản", "VRE.VN": "Bất động sản",
        "KDH.VN": "Bất động sản", "NLG.VN": "Bất động sản", "NVL.VN": "Bất động sản", "PDR.VN": "Bất động sản",
        "SSI.VN": "Chứng khoán", "BVH.VN": "Bảo hiểm",
        "FPT.VN": "Công nghệ", "MWG.VN": "Bán lẻ", "MSN.VN": "Tiêu dùng",
        "VNM.VN": "Tiêu dùng", "SAB.VN": "Tiêu dùng",
        "HPG.VN": "Vật liệu", "GVR.VN": "Công nghiệp",
        "GAS.VN": "Năng lượng", "PLX.VN": "Năng lượng", "POW.VN": "Năng lượng"
    }

    loadings = pd.DataFrame(eigenvectors_sorted[:, :5], columns=[f'PC{i}' for i in range(1, 6)], index=df_prices.columns)
    loadings['Sector'] = loadings.index.map(sector_mapping)
    sector_analysis = loadings.groupby('Sector').mean(numeric_only=True)

    col1, col2 = st.columns([1.5, 1])

    with col1:
        st.markdown("**Bản đồ nhiệt Trọng số trung bình theo ngành:**")
        fig_heat = px.imshow(sector_analysis, text_auto=".3f", color_continuous_scale='RdBu_r', aspect="auto")
        fig_heat.update_layout(height=400)
        st.plotly_chart(fig_heat, use_container_width=True)

    with col2:
        st.markdown("**Chi tiết PC2 & PC3:**")
        st.dataframe(loadings[['Sector', 'PC2', 'PC3']].style.background_gradient(cmap='RdBu_r', axis=0), height=400)

    st.markdown("""
    <div class="breakthrough-box">
    <b>Kết luận chuyên sâu từ mô hình:</b><br>
    Việc gom cụm các hệ số Eigenvectors xác nhận có tồn tại các <i>'Sector Factors'</i> rõ rệt ẩn trong cấu trúc VN30:<br>
    <ul>
        <li><b>PC2 (Sự phân kỳ Ngành):</b> Biểu đồ Heatmap cho thấy PC2 thường là điểm đối trọng giữa nhóm ngành <b>Bất động sản</b> và nhóm <b>Năng lượng/Công nghiệp</b>.</li>
        <li><b>PC3 (Luân chuyển Tài chính):</b> Thành phần này thường phản ánh sự dịch chuyển dòng tiền liên quan đến nhóm <b>Ngân hàng & Chứng khoán</b> so với phần còn lại của thị trường.</li>
    </ul>
    </div>
    """, unsafe_allow_html=True)